DevsTutorialCenterMVC/Controllers/EditorController.cs
using DevsTutorialCenterMVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace DevsTutorialCenterMVC.Controllers;

[Route("editor")]
public class EditorController : Controller
{
    private readonly EditorService _editorService;
    private readonly BlogPostService _blogPostService;

    public EditorController(EditorService editorService, BlogPostService blogPostService)
    {
        _editorService = editorService;
        _blogPostService = blogPostService;
    }
    
    [HttpGet("")]
    public async Task<IActionResult> Index()
    {
        var model = await _editorService.GetPendingArticles();
        return View(model);
    }
    
    [HttpPost("approve/{articleId}")]
    public async Task<IActionResult> ApproveArticle(string articleId)
    {
        var isSuccessful = await _editorService.ApproveArticle(articleId);
        if (!isSuccessful) return BadRequest();
        return RedirectToAction("Index");
    }
    
    [HttpPost("reject/{articleId}")]
    public async Task<IActionResult> RejectArticle(string articleId)
    {
        var isSuccessful = await _editorService.RejectArticle(articleId);
        if (!isSuccessful) return BadRequest();
        return RedirectToAction("Index");
    }
    
    [HttpGet("articles/{articleId}")]
    public async Task<IActionResult> OpenArticle(string articleId)
    {
        var article = await _blogPostService.GetArticleById(articleId);
        return View(article);
    }
}

DevsTutorialCenterMVC/Views/Editor/Index.cshtml
@model IEnumerable<DevsTutorialCenterMVC.Models.Api.BlogPostVM>

<partial name="_LandingPageNavPartial"/>

<div class="container mt-2">

    <div class="flex flex-col justify-start items-start mt-10 md:flex-row md:space-x-10 ">
        <div class="flex flex-col space-y-8">
            @foreach (var post in Model)
            {
                <partial name="Components/_BlogPostEditorItemPartial" model="@post"/>
            }
        </div>
    </div>
</div>

DevsTutorialCenterMVC/Views/Editor/OpenArticle.cshtml
@using DevsTutorialCenterMVC.Utilities
@model SingleArticleVM;

<partial name="_LandingPageNavPartial"/>

<div class="container">
    <div class="flex my-5 space-x-3 justify-end">
        <form method="POST" asp-controller="Editor" asp-action="ApproveArticle" asp-route-articleId="@Model.Id">
            <button type="submit" class="button">Approve</button>
        </form>
        <form method="POST" asp-controller="Editor" asp-action="RejectArticle" asp-route-articleId="@Model.Id">
            <button type="submit" class="button-secondary">Decline</button>
        </form>
    </div>
    
    <div class="flex mt-2 space-x-5">
        <div class="w-full">
            <div class="relative">
                <img class="-z-50 aspect-[16/10] w-full object-cover object-center" src="@Model.ImageUrl" alt=""/>
                <div class="absolute -mt-36 w-full px-6">
                    <div class="w-full bg-white p-6">
                        <div class="flex items-center space-x-4">
                            <div class="inline-flex space-x-5 rounded-full bg-gray-100 px-3 py-1 text-sm uppercase text-slate-500">@Model.TagName</div>
                            <div class="w-4 border-t border-gray-300"></div>
                            <div class="text-sm text-gray-500">@Model.CreatedOn.FormatDate() </div>
                        </div>
                        <p class="mt-4 text-2xl font-medium">@Model.Title</p>
                        <p class="mt-6 text-sm">@Model.Text</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>